version: '3'

services:

  db:
    image: mariadb:10
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_USER: vikunja
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: vikunja
    volumes:
      - ./db:/var/lib/mysql
    restart: unless-stopped
    
  api:
    image: vikunja/api
    environment:
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: secret
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_JWTSECRET: jwt_secret #a super secure random secret
      VIKUNJA_SERVICE_FRONTENDURL: http://localhost:8200/ # localhost, URL publica o tu IP
    ports:
      - 8100:3456
    volumes:
      - ./files:/app/vikunja/files
    depends_on:
      - db
    restart: unless-stopped
    
  frontend:
    image: vikunja/frontend
    ports:
      - 8200:80
    environment:
      VIKUNJA_API_URL: http://localhost:8100/api/v1  # localhost o tu IP
    restart: unless-stopped

    

    
